name: wargame
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  get_storage: ^2.0.3
  
  hasura_connect: ^4.0.0+2
  graphql: ^5.0.0
  flutter_svg: ^1.0.3
  resultlr: 
    git: 
      url: https://github.com/hbedford/resultlr.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/i18n/

